spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.105/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell

wechat:
  mpAppId: wxbee2a7f6374a9eab
  mpAppSecret: 78c200afbc5fe986fec0b129f7b41033
  mchId:
  mchkey:
  keyPath: /Users/mac/springcloud/h5.p12
  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
#logging:
#  pattern:
#    console:  "%d - %msg%n"
## path: /var/log/tomcat/
#file: /var/log/tomcat/sell.log
#level: debug